# ==========================================
# parameters.py
# ------------------------------------------
# Global configuration file defining:
#   - Day names
#   - Feature categories
#   - Algorithm-specific feature mappings
# ==========================================

# ------------------------------------------
# Feature Categories
# ------------------------------------------
# Broad categories of features extracted from multimodal data sources.
feature_categories = [
    "f_call",     # Phone call features
    "f_blue",     # Bluetooth features
    "f_wifi",     # Wi-Fi features
    "f_slp",      # Sleep-related features (Fitbit)
    "f_steps",    # Step count and activity features
    "f_loc",      # Location-based mobility features
    "f_screen"    # Screen usage features
]


# ------------------------------------------
# Algorithm-Specific Feature Dictionaries
# ------------------------------------------
# Mapping of algorithm identifiers to their corresponding feature sets.
# Each key corresponds to an algorithm name used in experiments or analysis.

algo_dict = {'ml_chikersal':[
            "f_loc:phone_locations_doryab_numberofsignificantplaces",
            "f_loc:phone_locations_doryab_numberlocationtransitions",
            "f_loc:phone_locations_doryab_radiusgyration",
            "f_loc:phone_locations_doryab_timeattop1location",
            "f_loc:phone_locations_doryab_timeattop2location",
            "f_loc:phone_locations_doryab_timeattop3location",
            "f_loc:phone_locations_doryab_movingtostaticratio",
            "f_loc:phone_locations_doryab_outlierstimepercent",
            "f_loc:phone_locations_doryab_avglengthstayatclusters",
            "f_loc:phone_locations_doryab_maxlengthstayatclusters",
            "f_loc:phone_locations_doryab_minlengthstayatclusters",
            "f_loc:phone_locations_doryab_stdlengthstayatclusters",
            "f_loc:phone_locations_doryab_locationentropy",
            "f_loc:phone_locations_doryab_normalizedlocationentropy",
            "f_loc:phone_locations_doryab_timeathome",
            "f_loc:phone_locations_locmap_duration_in_locmap_study",
            "f_loc:phone_locations_locmap_percent_in_locmap_study",
            "f_loc:phone_locations_locmap_duration_in_locmap_exercise",
            "f_loc:phone_locations_locmap_percent_in_locmap_exercise",
            "f_loc:phone_locations_locmap_duration_in_locmap_greens",
            "f_loc:phone_locations_locmap_percent_in_locmap_greens",
            "f_screen:phone_screen_rapids_countepisodeunlock",
            "f_screen:phone_screen_rapids_sumdurationunlock",
            "f_screen:phone_screen_rapids_maxdurationunlock",
            "f_screen:phone_screen_rapids_mindurationunlock",
            "f_screen:phone_screen_rapids_avgdurationunlock",
            "f_screen:phone_screen_rapids_stddurationunlock",
            "f_screen:phone_screen_rapids_firstuseafter00unlock",
            "f_slp:fitbit_sleep_intraday_rapids_countepisodeasleepunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_countepisodeawakeunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_sumdurationasleepunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_sumdurationawakeunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_avgdurationasleepunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_avgdurationawakeunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_mindurationasleepunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_mindurationawakeunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_maxdurationasleepunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_maxdurationawakeunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_ratiocountasleepunifiedwithinmain",
            "f_slp:fitbit_sleep_intraday_rapids_ratiocountawakeunifiedwithinmain",
            "f_slp:fitbit_sleep_intraday_rapids_ratiodurationasleepunifiedwithinmain",
            "f_slp:fitbit_sleep_intraday_rapids_ratiodurationawakeunifiedwithinmain",
            "f_steps:fitbit_steps_intraday_rapids_sumsteps",
            "f_steps:fitbit_steps_intraday_rapids_countepisodesedentarybout",
            "f_steps:fitbit_steps_intraday_rapids_maxdurationsedentarybout",
            "f_steps:fitbit_steps_intraday_rapids_mindurationsedentarybout",
            "f_steps:fitbit_steps_intraday_rapids_avgdurationsedentarybout",
            "f_steps:fitbit_steps_intraday_rapids_countepisodeactivebout",
            "f_steps:fitbit_steps_intraday_rapids_maxdurationactivebout",
            "f_steps:fitbit_steps_intraday_rapids_mindurationactivebout",
            "f_steps:fitbit_steps_intraday_rapids_avgdurationactivebout",
        ],

'dl_feat':[
            "f_screen:phone_screen_rapids_countepisodeunlock_locmap_exercise:afternoon",
            "f_screen:phone_screen_rapids_countepisodeunlock_locmap_greens:night",
            "f_screen:phone_screen_rapids_firstuseafter00unlock_locmap_exercise:allday",
            "f_screen:phone_screen_rapids_firstuseafter00unlock_locmap_exercise:night",
            "f_screen:phone_screen_rapids_firstuseafter00unlock_locmap_home:night",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_exercise:evening",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_greens:allday",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_greens:night",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_home:night",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_study:evening",
            "f_screen:phone_screen_rapids_mindurationunlock_locmap_exercise:evening",
            "f_screen:phone_screen_rapids_mindurationunlock_locmap_exercise:morning",
            "f_screen:phone_screen_rapids_stddurationunlock_locmap_exercise:evening",
            "f_screen:phone_screen_rapids_stddurationunlock_locmap_home:night",
            "f_screen:phone_screen_rapids_sumdurationunlock_locmap_exercise:night",
            "f_screen:phone_screen_rapids_sumdurationunlock_locmap_home:night",
            "f_screen:phone_screen_rapids_sumdurationunlock_locmap_living:night",
            "f_slp:fitbit_sleep_intraday_rapids_maxdurationasleepunifiedmain:night",
            "f_slp:fitbit_sleep_intraday_rapids_maxdurationawakeunifiedmain:night",
            "f_slp:fitbit_sleep_intraday_rapids_mindurationasleepunifiedmain:afternoon",
            "f_slp:fitbit_sleep_intraday_rapids_mindurationasleepunifiedmain:night",
            "f_slp:fitbit_sleep_intraday_rapids_sumdurationasleepunifiedmain:allday",
            "f_slp:fitbit_sleep_summary_rapids_avgdurationasleepmain:allday",
            "f_slp:fitbit_sleep_summary_rapids_avgdurationinbedmain:allday",
            "f_slp:fitbit_sleep_summary_rapids_lastbedtimemain:allday",
            "f_slp:fitbit_sleep_summary_rapids_sumdurationasleepmain:allday",
            "f_slp:fitbit_sleep_summary_rapids_sumdurationinbedmain:allday",
            "f_steps:fitbit_steps_intraday_rapids_countepisodesedentarybout:evening",
            "f_steps:fitbit_steps_intraday_rapids_maxdurationactivebout:morning",
            "f_steps:fitbit_steps_intraday_rapids_maxsteps:evening",
            "f_steps:fitbit_steps_intraday_rapids_mindurationactivebout:evening",

            "f_loc:phone_locations_doryab_locationentropy_norm:afternoon",
            "f_loc:phone_locations_doryab_loglocationvariance_norm:allday",
            "f_loc:phone_locations_doryab_minlengthstayatclusters_norm:afternoon",
            "f_loc:phone_locations_doryab_outlierstimepercent_norm:morning",
            "f_loc:phone_locations_doryab_radiusgyration_norm:allday",
            "f_screen:phone_screen_rapids_avgdurationunlock_locmap_exercise_norm:evening",
            "f_screen:phone_screen_rapids_avgdurationunlock_locmap_greens_norm:night",
            "f_screen:phone_screen_rapids_firstuseafter00unlock_locmap_exercise_norm:allday",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_exercise_norm:afternoon",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_exercise_norm:evening",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_exercise_norm:night",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_greens_norm:evening",
            "f_screen:phone_screen_rapids_sumdurationunlock_locmap_home_norm:morning",
            "f_slp:fitbit_sleep_intraday_rapids_maxdurationawakeunifiedmain_norm:afternoon",
            "f_slp:fitbit_sleep_intraday_rapids_ratiodurationasleepunifiedwithinmain_norm:afternoon",
            "f_slp:fitbit_sleep_intraday_rapids_ratiodurationawakeunifiedwithinmain_norm:afternoon",
            "f_steps:fitbit_steps_intraday_rapids_countepisodesedentarybout_norm:afternoon",
            "f_steps:fitbit_steps_intraday_rapids_maxdurationsedentarybout_norm:night",
            "f_steps:fitbit_steps_intraday_rapids_stdsteps_norm:morning",
            "f_screen:phone_screen_rapids_countepisodeunlock_locmap_exercise:afternoon",
            "f_screen:phone_screen_rapids_countepisodeunlock_locmap_greens:night",
            "f_screen:phone_screen_rapids_firstuseafter00unlock_locmap_exercise:allday",
            "f_screen:phone_screen_rapids_firstuseafter00unlock_locmap_exercise:night",
            "f_screen:phone_screen_rapids_firstuseafter00unlock_locmap_home:night",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_exercise:evening",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_greens:allday",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_greens:night",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_home:night",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_study:evening",
            "f_screen:phone_screen_rapids_mindurationunlock_locmap_exercise:evening",
            "f_screen:phone_screen_rapids_mindurationunlock_locmap_exercise:morning",
            "f_screen:phone_screen_rapids_stddurationunlock_locmap_exercise:evening",
            "f_screen:phone_screen_rapids_stddurationunlock_locmap_home:night",
            "f_screen:phone_screen_rapids_sumdurationunlock_locmap_exercise:night",
            "f_screen:phone_screen_rapids_sumdurationunlock_locmap_home:night",
            "f_screen:phone_screen_rapids_sumdurationunlock_locmap_living:night",
            "f_slp:fitbit_sleep_intraday_rapids_maxdurationasleepunifiedmain:night",
            "f_slp:fitbit_sleep_intraday_rapids_maxdurationawakeunifiedmain:night",
            "f_slp:fitbit_sleep_intraday_rapids_mindurationasleepunifiedmain:afternoon",
            "f_slp:fitbit_sleep_intraday_rapids_mindurationasleepunifiedmain:night",
            "f_slp:fitbit_sleep_intraday_rapids_sumdurationasleepunifiedmain:allday",
            "f_slp:fitbit_sleep_summary_rapids_avgdurationasleepmain:allday",
            "f_slp:fitbit_sleep_summary_rapids_avgdurationinbedmain:allday",
            "f_slp:fitbit_sleep_summary_rapids_lastbedtimemain:allday",
            "f_slp:fitbit_sleep_summary_rapids_sumdurationasleepmain:allday",
            "f_slp:fitbit_sleep_summary_rapids_sumdurationinbedmain:allday",
            "f_steps:fitbit_steps_intraday_rapids_countepisodesedentarybout:evening",
            "f_steps:fitbit_steps_intraday_rapids_maxdurationactivebout:morning",
            "f_steps:fitbit_steps_intraday_rapids_maxsteps:evening",
            "f_steps:fitbit_steps_intraday_rapids_mindurationactivebout:evening",
            "f_blue:phone_bluetooth_doryab_uniquedevicesown:night",
            "f_call:phone_calls_rapids_incoming_distinctcontacts:afternoon",

            "f_loc:phone_locations_doryab_locationentropy_norm:afternoon",
            "f_loc:phone_locations_doryab_loglocationvariance_norm:allday",
            "f_loc:phone_locations_doryab_minlengthstayatclusters_norm:afternoon",
            "f_loc:phone_locations_doryab_outlierstimepercent_norm:morning",
            "f_loc:phone_locations_doryab_radiusgyration_norm:allday",
            "f_screen:phone_screen_rapids_avgdurationunlock_locmap_exercise_norm:evening",
            "f_screen:phone_screen_rapids_avgdurationunlock_locmap_greens_norm:night",
            "f_screen:phone_screen_rapids_firstuseafter00unlock_locmap_exercise_norm:allday",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_exercise_norm:afternoon",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_exercise_norm:evening",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_exercise_norm:night",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_greens_norm:evening",
            "f_screen:phone_screen_rapids_sumdurationunlock_locmap_home_norm:morning",
            "f_slp:fitbit_sleep_intraday_rapids_maxdurationawakeunifiedmain_norm:afternoon",
            "f_slp:fitbit_sleep_intraday_rapids_ratiodurationasleepunifiedwithinmain_norm:afternoon",
            "f_slp:fitbit_sleep_intraday_rapids_ratiodurationawakeunifiedwithinmain_norm:afternoon",
            "f_steps:fitbit_steps_intraday_rapids_countepisodesedentarybout_norm:afternoon",
            "f_steps:fitbit_steps_intraday_rapids_maxdurationsedentarybout_norm:night",
            "f_steps:fitbit_steps_intraday_rapids_stdsteps_norm:morning",
            "f_blue:phone_bluetooth_doryab_countscansmostfrequentdeviceacrossdatasetown_norm:night",
            "f_call:phone_calls_rapids_outgoing_count_norm:afternoon",
        ],
           
           
'ml_xu_personalized': [ "f_loc:phone_locations_doryab_numberofsignificantplaces",
            "f_loc:phone_locations_doryab_numberlocationtransitions",
            "f_loc:phone_locations_doryab_radiusgyration",
            "f_loc:phone_locations_doryab_timeattop1location",
            "f_loc:phone_locations_doryab_timeattop2location",
            "f_loc:phone_locations_doryab_timeattop3location",
            "f_loc:phone_locations_doryab_movingtostaticratio",
            "f_loc:phone_locations_doryab_outlierstimepercent",
            "f_loc:phone_locations_doryab_avglengthstayatclusters",
            "f_loc:phone_locations_doryab_maxlengthstayatclusters",
            "f_loc:phone_locations_doryab_minlengthstayatclusters",
            "f_loc:phone_locations_doryab_stdlengthstayatclusters",
            "f_loc:phone_locations_doryab_locationentropy",
            "f_loc:phone_locations_doryab_normalizedlocationentropy",
            "f_loc:phone_locations_doryab_timeathome",
            "f_loc:phone_locations_barnett_circdnrtn",
            "f_loc:phone_locations_doryab_loglocationvariance",
            "f_loc:phone_locations_doryab_totaldistance",
            "f_loc:phone_locations_locmap_duration_in_locmap_study",
            "f_loc:phone_locations_locmap_percent_in_locmap_study",
            "f_loc:phone_locations_locmap_duration_in_locmap_exercise",
            "f_loc:phone_locations_locmap_percent_in_locmap_exercise",
            "f_loc:phone_locations_locmap_duration_in_locmap_greens",
            "f_loc:phone_locations_locmap_percent_in_locmap_greens",
            "f_screen:phone_screen_rapids_countepisodeunlock",
            "f_screen:phone_screen_rapids_sumdurationunlock",
            "f_screen:phone_screen_rapids_maxdurationunlock",
            "f_screen:phone_screen_rapids_mindurationunlock",
            "f_screen:phone_screen_rapids_avgdurationunlock",
            "f_screen:phone_screen_rapids_stddurationunlock",
            "f_screen:phone_screen_rapids_firstuseafter00unlock",
            "f_slp:fitbit_sleep_intraday_rapids_countepisodeasleepunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_countepisodeawakeunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_sumdurationasleepunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_sumdurationawakeunifiedmain", 
            "f_slp:fitbit_sleep_intraday_rapids_avgdurationasleepunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_avgdurationawakeunifiedmain", 
            "f_slp:fitbit_sleep_intraday_rapids_mindurationasleepunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_mindurationawakeunifiedmain", 
            "f_slp:fitbit_sleep_intraday_rapids_maxdurationasleepunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_maxdurationawakeunifiedmain", 
            "f_slp:fitbit_sleep_intraday_rapids_ratiocountasleepunifiedwithinmain",
            "f_slp:fitbit_sleep_intraday_rapids_ratiocountawakeunifiedwithinmain",
            "f_slp:fitbit_sleep_intraday_rapids_ratiodurationasleepunifiedwithinmain",
            "f_slp:fitbit_sleep_intraday_rapids_ratiodurationawakeunifiedwithinmain",
            "f_steps:fitbit_steps_intraday_rapids_sumsteps",
            "f_steps:fitbit_steps_intraday_rapids_countepisodesedentarybout",
            "f_steps:fitbit_steps_intraday_rapids_maxdurationsedentarybout",
            "f_steps:fitbit_steps_intraday_rapids_mindurationsedentarybout",
            "f_steps:fitbit_steps_intraday_rapids_avgdurationsedentarybout",
            "f_steps:fitbit_steps_intraday_rapids_countepisodeactivebout",
            "f_steps:fitbit_steps_intraday_rapids_maxdurationactivebout",
            "f_steps:fitbit_steps_intraday_rapids_mindurationactivebout",
            "f_steps:fitbit_steps_intraday_rapids_avgdurationactivebout",
        ],
           
'ml_xu_interpretable':
           [
            "f_screen:phone_screen_rapids_avgdurationunlock",
            "f_screen:phone_screen_rapids_stddurationunlock",
            "f_screen:phone_screen_rapids_countepisodeunlock",
            "f_screen:phone_screen_rapids_sumdurationunlock",
            "f_slp:fitbit_sleep_intraday_rapids_maxdurationasleepunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_countepisodeasleepunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_countepisodeawakeunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_ratiodurationasleepunifiedwithinmain",
            "f_slp:fitbit_sleep_intraday_rapids_sumdurationasleepunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_sumdurationawakeunifiedmain",
            "f_steps:fitbit_steps_intraday_rapids_avgdurationactivebout",
            "f_steps:fitbit_steps_intraday_rapids_avgdurationsedentarybout",
            "f_steps:fitbit_steps_intraday_rapids_countepisodeactivebout",
            "f_steps:fitbit_steps_intraday_rapids_countepisodesedentarybout",
            "f_steps:fitbit_steps_intraday_rapids_sumsteps",
            "f_loc:phone_locations_barnett_circdnrtn",
            "f_loc:phone_locations_doryab_timeathome",
            "f_loc:phone_locations_doryab_locationentropy",
            "f_loc:phone_locations_doryab_loglocationvariance",
            "f_loc:phone_locations_doryab_avglengthstayatclusters",
            "f_loc:phone_locations_doryab_movingtostaticratio",
            "f_loc:phone_locations_doryab_numberlocationtransitions",
            "f_loc:phone_locations_doryab_numberofsignificantplaces",
            "f_loc:phone_locations_doryab_outlierstimepercent",
            "f_loc:phone_locations_doryab_radiusgyration",
            "f_loc:phone_locations_doryab_totaldistance",
            "f_loc:phone_locations_locmap_duration_in_locmap_study",
            "f_loc:phone_locations_locmap_percent_in_locmap_study",
            "f_loc:phone_locations_locmap_duration_in_locmap_exercise",
            "f_loc:phone_locations_locmap_percent_in_locmap_exercise",
            "f_loc:phone_locations_locmap_duration_in_locmap_greens",
            "f_loc:phone_locations_locmap_percent_in_locmap_greens",
        ],
           
'ml_wang':["f_slp:fitbit_sleep_summary_rapids_sumdurationinbedmain:allday",
            "f_slp:fitbit_sleep_summary_rapids_firstbedtimemain:allday",
            "f_slp:fitbit_sleep_summary_rapids_firstwaketimemain:allday",
            "f_steps:fitbit_steps_intraday_rapids_sumdurationsedentarybout:allday",
            "f_screen:phone_screen_rapids_sumdurationunlock:allday",
            "f_screen:phone_screen_rapids_sumdurationunlock_locmap_study:allday",
            "f_screen:phone_screen_rapids_sumdurationunlock_locmap_living:allday",
            "f_loc:phone_locations_doryab_numberofsignificantplaces:allday",
            "f_loc:phone_locations_barnett_hometime:allday",
            "f_loc:phone_locations_locmap_duration_in_locmap_study:allday"],

'ml_saeb':["f_loc:phone_locations_doryab_loglocationvariance:allday",
            "f_loc:phone_locations_doryab_numberofsignificantplaces:allday",
            "f_loc:phone_locations_doryab_locationentropy:allday",
            "f_loc:phone_locations_doryab_normalizedlocationentropy:allday",
            "f_loc:phone_locations_barnett_hometime:allday",
            "f_loc:phone_locations_barnett_circdnrtn:allday",
            "f_loc:phone_locations_doryab_movingtostaticratio:allday",
            "f_loc:phone_locations_barnett_disttravelled:allday",
            "f_screen:phone_screen_rapids_sumdurationunlock:allday",
            "f_screen:phone_screen_rapids_countepisodeunlock:allday",
        ],
          
"allday": ['f_screen:phone_screen_rapids_firstuseafter00unlock_locmap_exercise:allday',
 'f_call:phone_calls_rapids_missed_timefirstcall:allday',
 'f_call:phone_calls_rapids_incoming_minduration:allday',
 'f_call:phone_calls_rapids_missed_timelastcall:allday',
 'f_screen:phone_screen_rapids_stddurationunlock_locmap_exercise:allday',
 'f_screen:phone_screen_rapids_mindurationunlock_locmap_exercise:allday',
 'f_call:phone_calls_rapids_incoming_stdduration:allday',
 'f_call:phone_calls_rapids_outgoing_modeduration:allday',
 'f_screen:phone_screen_rapids_maxdurationunlock_locmap_living:allday',
 'f_screen:phone_screen_rapids_maxdurationunlock_locmap_exercise:allday',
 'f_screen:phone_screen_rapids_countepisodeunlock_locmap_living:allday',
 'f_call:phone_calls_rapids_incoming_timelastcall:allday',
 'f_slp:fitbit_sleep_intraday_rapids_sumdurationasleepunifiedmain:allday',
 'f_slp:fitbit_sleep_intraday_rapids_stddurationasleepunifiedmain:allday',
 'f_call:phone_calls_rapids_outgoing_meanduration:allday',
 'f_call:phone_calls_rapids_incoming_timefirstcall:allday',
 'f_call:phone_calls_rapids_outgoing_timefirstcall:allday',
 'f_screen:phone_screen_rapids_avgdurationunlock_locmap_exercise:allday',
 'f_screen:phone_screen_rapids_mindurationunlock_locmap_living:allday',
 'f_screen:phone_screen_rapids_avgdurationunlock_locmap_home:allday'],
          }


# ------------------------------------------
# Day Names
# ------------------------------------------
# Ordered list of day names used in analysis or visualization.
day_name = [
    'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'
]


